# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /System/Volumes/Data/Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /System/Volumes/Data/Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/craig/Code/game_jam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/craig/Code/game_jam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/System/Volumes/Data/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/System/Volumes/Data/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/craig/Code/game_jam/CMakeFiles /Users/craig/Code/game_jam//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/craig/Code/game_jam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mygame

# Build rule for target.
mygame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mygame
.PHONY : mygame

# fast build rule for target.
mygame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/build
.PHONY : mygame/fast

#=============================================================================
# Target rules for targets named cute

# Build rule for target.
cute: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cute
.PHONY : cute

# fast build rule for target.
cute/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/cute.dir/build.make _deps/cute-build/CMakeFiles/cute.dir/build
.PHONY : cute/fast

#=============================================================================
# Target rules for targets named physfs

# Build rule for target.
physfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 physfs
.PHONY : physfs

# fast build rule for target.
physfs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/physfs.dir/build.make _deps/cute-build/CMakeFiles/physfs.dir/build
.PHONY : physfs/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/tests.dir/build.make _deps/cute-build/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named easysprite

# Build rule for target.
easysprite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 easysprite
.PHONY : easysprite

# fast build rule for target.
easysprite/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/easysprite.dir/build.make _deps/cute-build/CMakeFiles/easysprite.dir/build
.PHONY : easysprite/fast

#=============================================================================
# Target rules for targets named basicecs

# Build rule for target.
basicecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicecs
.PHONY : basicecs

# fast build rule for target.
basicecs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/basicecs.dir/build.make _deps/cute-build/CMakeFiles/basicecs.dir/build
.PHONY : basicecs/fast

#=============================================================================
# Target rules for targets named basicserialization

# Build rule for target.
basicserialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicserialization
.PHONY : basicserialization

# fast build rule for target.
basicserialization/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/basicserialization.dir/build.make _deps/cute-build/CMakeFiles/basicserialization.dir/build
.PHONY : basicserialization/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/imgui.dir/build.make _deps/cute-build/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named textdrawing

# Build rule for target.
textdrawing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 textdrawing
.PHONY : textdrawing

# fast build rule for target.
textdrawing/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/textdrawing.dir/build.make _deps/cute-build/CMakeFiles/textdrawing.dir/build
.PHONY : textdrawing/fast

#=============================================================================
# Target rules for targets named basicsprite

# Build rule for target.
basicsprite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicsprite
.PHONY : basicsprite

# fast build rule for target.
basicsprite/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/basicsprite.dir/build.make _deps/cute-build/CMakeFiles/basicsprite.dir/build
.PHONY : basicsprite/fast

#=============================================================================
# Target rules for targets named basicshapes

# Build rule for target.
basicshapes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicshapes
.PHONY : basicshapes

# fast build rule for target.
basicshapes/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/basicshapes.dir/build.make _deps/cute-build/CMakeFiles/basicshapes.dir/build
.PHONY : basicshapes/fast

#=============================================================================
# Target rules for targets named windowresizing

# Build rule for target.
windowresizing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 windowresizing
.PHONY : windowresizing

# fast build rule for target.
windowresizing/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/windowresizing.dir/build.make _deps/cute-build/CMakeFiles/windowresizing.dir/build
.PHONY : windowresizing/fast

#=============================================================================
# Target rules for targets named basicinput

# Build rule for target.
basicinput: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basicinput
.PHONY : basicinput

# fast build rule for target.
basicinput/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/basicinput.dir/build.make _deps/cute-build/CMakeFiles/basicinput.dir/build
.PHONY : basicinput/fast

#=============================================================================
# Target rules for targets named windowevents

# Build rule for target.
windowevents: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 windowevents
.PHONY : windowevents

# fast build rule for target.
windowevents/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/windowevents.dir/build.make _deps/cute-build/CMakeFiles/windowevents.dir/build
.PHONY : windowevents/fast

#=============================================================================
# Target rules for targets named window

# Build rule for target.
window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window
.PHONY : window

# fast build rule for target.
window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/window.dir/build.make _deps/cute-build/CMakeFiles/window.dir/build
.PHONY : window/fast

#=============================================================================
# Target rules for targets named tint

# Build rule for target.
tint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tint
.PHONY : tint

# fast build rule for target.
tint/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/tint.dir/build.make _deps/cute-build/CMakeFiles/tint.dir/build
.PHONY : tint/fast

#=============================================================================
# Target rules for targets named docsparser

# Build rule for target.
docsparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docsparser
.PHONY : docsparser

# fast build rule for target.
docsparser/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/docsparser.dir/build.make _deps/cute-build/CMakeFiles/docsparser.dir/build
.PHONY : docsparser/fast

#=============================================================================
# Target rules for targets named scratch

# Build rule for target.
scratch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch
.PHONY : scratch

# fast build rule for target.
scratch/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/scratch.dir/build.make _deps/cute-build/CMakeFiles/scratch.dir/build
.PHONY : scratch/fast

#=============================================================================
# Target rules for targets named echo

# Build rule for target.
echo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo
.PHONY : echo

# fast build rule for target.
echo/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/echo.dir/build.make _deps/cute-build/CMakeFiles/echo.dir/build
.PHONY : echo/fast

#=============================================================================
# Target rules for targets named https

# Build rule for target.
https: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 https
.PHONY : https

# fast build rule for target.
https/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/https.dir/build.make _deps/cute-build/CMakeFiles/https.dir/build
.PHONY : https/fast

#=============================================================================
# Target rules for targets named spaceshooter

# Build rule for target.
spaceshooter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spaceshooter
.PHONY : spaceshooter

# fast build rule for target.
spaceshooter/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/spaceshooter.dir/build.make _deps/cute-build/CMakeFiles/spaceshooter.dir/build
.PHONY : spaceshooter/fast

#=============================================================================
# Target rules for targets named draw_to_texture

# Build rule for target.
draw_to_texture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 draw_to_texture
.PHONY : draw_to_texture

# fast build rule for target.
draw_to_texture/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/draw_to_texture.dir/build.make _deps/cute-build/CMakeFiles/draw_to_texture.dir/build
.PHONY : draw_to_texture/fast

#=============================================================================
# Target rules for targets named hello_triangle

# Build rule for target.
hello_triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_triangle
.PHONY : hello_triangle

# fast build rule for target.
hello_triangle/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/hello_triangle.dir/build.make _deps/cute-build/CMakeFiles/hello_triangle.dir/build
.PHONY : hello_triangle/fast

#=============================================================================
# Target rules for targets named waves

# Build rule for target.
waves: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 waves
.PHONY : waves

# fast build rule for target.
waves/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/waves.dir/build.make _deps/cute-build/CMakeFiles/waves.dir/build
.PHONY : waves/fast

#=============================================================================
# Target rules for targets named shallow_water

# Build rule for target.
shallow_water: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shallow_water
.PHONY : shallow_water

# fast build rule for target.
shallow_water/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/shallow_water.dir/build.make _deps/cute-build/CMakeFiles/shallow_water.dir/build
.PHONY : shallow_water/fast

#=============================================================================
# Target rules for targets named noise

# Build rule for target.
noise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 noise
.PHONY : noise

# fast build rule for target.
noise/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/noise.dir/build.make _deps/cute-build/CMakeFiles/noise.dir/build
.PHONY : noise/fast

#=============================================================================
# Target rules for targets named fetch_image

# Build rule for target.
fetch_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fetch_image
.PHONY : fetch_image

# fast build rule for target.
fetch_image/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cute-build/CMakeFiles/fetch_image.dir/build.make _deps/cute-build/CMakeFiles/fetch_image.dir/build
.PHONY : fetch_image/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... SDL2-static"
	@echo "... SDL2_test"
	@echo "... SDL2main"
	@echo "... basicecs"
	@echo "... basicinput"
	@echo "... basicserialization"
	@echo "... basicshapes"
	@echo "... basicsprite"
	@echo "... cute"
	@echo "... docsparser"
	@echo "... draw_to_texture"
	@echo "... easysprite"
	@echo "... echo"
	@echo "... fetch_image"
	@echo "... hello_triangle"
	@echo "... https"
	@echo "... imgui"
	@echo "... mygame"
	@echo "... noise"
	@echo "... physfs"
	@echo "... scratch"
	@echo "... shallow_water"
	@echo "... spaceshooter"
	@echo "... tests"
	@echo "... textdrawing"
	@echo "... tint"
	@echo "... waves"
	@echo "... window"
	@echo "... windowevents"
	@echo "... windowresizing"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

