
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/System/Volumes/Data/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.4.0 - x86_64
...
